[project]
name = "e2e-saas-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Prayogi Dwi Wibisono", email = "wibssono@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "duckdb>=1.5.5",
    "polars>=1.44.2",
    "pytest>=9.1.1",
    "ruff>=0.16.7",
]

[project.scripts]
e2e-saas-pipeline = "e2e_saas_pipeline:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
